global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: node-exporter
    static_configs:
    - targets: ['167.172.35.56:9100']

  - job_name: cadvisor
    static_configs:
    - targets: ['167.172.35.56:8080']

  - job_name: mysqld_exporter
    honor_labels: true
    static_configs:
    - targets: ['167.172.35.56:9111']
